modLoader="javafml"
loaderVersion="[40,)"
license="Copyright 2022 (c) Kaka. All rights reserved."

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description='''
${mod_name} ${version} by ${mod_author}.
'''