package com.kakaouo.mods.kacosmetics.util;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.PartDefinition;

public enum ModelModifier {
    ;

    public static void addGrassToPartDefinition(PartDefinition head) {
        @SuppressWarnings("UnnecessaryLocalVariable")
        PartDefinition Head = head;
        // Code below is generated by Blockbench

        PartDefinition grass_root_r1 = Head.addOrReplaceChild("grass_root_r1", CubeListBuilder.create().texOffs(62, 42).addBox(-0.5F, -0.975F, -0.5F, 1.0F, 4.0F, 0.0F, new CubeDeformation(0.001F)), PartPose.offsetAndRotation(0.0F, -11.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition grass_stem = Head.addOrReplaceChild("grass_stem", CubeListBuilder.create().texOffs(60, 40).addBox(-1.0F, -0.5F, 0.0F, 2.0F, 1.0F, 0.0F, new CubeDeformation(0.001F)), PartPose.offsetAndRotation(0.0F, -12.0F, 0.5F, -0.6545F, 0.0F, 0.0F));
        PartDefinition left_leave_r1 = grass_stem.addOrReplaceChild("left_leave_r1", CubeListBuilder.create().texOffs(58, 32).addBox(-3.95F, -37.0F, 0.3F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.01F)), PartPose.offsetAndRotation(0.0F, 35.5F, 0.0F, 0.0F, -0.3054F, 0.0F));
        PartDefinition right_leave_r1 = grass_stem.addOrReplaceChild("right_leave_r1", CubeListBuilder.create().texOffs(58, 36).addBox(0.95F, -37.0F, 0.3F, 3.0F, 3.0F, 0.0F, new CubeDeformation(0.01F)), PartPose.offsetAndRotation(0.0F, 35.5F, 0.0F, 0.0F, 0.3054F, 0.0F));
    }

    public static void addCatEarsToPartDefinition(PartDefinition head) {
        @SuppressWarnings("UnnecessaryLocalVariable")
        PartDefinition Head = head;
        // Code below is generated by Blockbench

        PartDefinition cat_ears = Head.addOrReplaceChild("cat_ears", CubeListBuilder.create(), PartPose.offset(0.0F, 0.0F, 0.0F));
        PartDefinition left_ear = cat_ears.addOrReplaceChild("left_ear", CubeListBuilder.create().texOffs(56, 18).mirror().addBox(-1.5F, -2.0F, -0.5F, 3.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)).mirror(false), PartPose.offset(2.5F, -8.0F, -0.5F));
        PartDefinition right_ear = cat_ears.addOrReplaceChild("right_ear", CubeListBuilder.create().texOffs(56, 18).addBox(-1.5F, -2.0F, -1.0F, 3.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(-2.5F, -8.0F, 0.0F));
    }

    public static void addCatTailToPartDefinition(PartDefinition body) {
        @SuppressWarnings("UnnecessaryLocalVariable")
        PartDefinition Body = body;
        // Code below is generated by Blockbench

        PartDefinition tail1 = Body.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(56, 22).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 11.0F, 0.75F, 0.7854F, 0.0F, 0.0F));
        PartDefinition tail2 = tail1.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(60, 22).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 8.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.7854F, 0.0F, 0.0F));
    }

    public static void addEeveeEarsToPartDefinition(PartDefinition head) {
        @SuppressWarnings("UnnecessaryLocalVariable")
        PartDefinition Head = head;
        // Code below is generated by Blockbench

        PartDefinition LeftEar = Head.addOrReplaceChild("LeftEar", CubeListBuilder.create().texOffs(58, 19).addBox(0.0F, -6.0F, -0.5F, 2.0F, 5.0F, 1.0F, new CubeDeformation(0.0F))
            .texOffs(58, 27).addBox(2.0F, -6.0F, -0.5F, 2.0F, 5.0F, 1.0F, new CubeDeformation(0.0F))
            .texOffs(56, 38).addBox(0.0F, -1.0F, -0.5F, 3.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
            .texOffs(58, 35).addBox(2.0F, -8.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
            .texOffs(56, 41).addBox(1.0F, -7.0F, -0.5F, 3.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.75F, -6.5F, 0.0F, -0.2182F, -0.1309F, 0.3054F));

        PartDefinition RightEar = Head.addOrReplaceChild("RightEar", CubeListBuilder.create().texOffs(58, 27).mirror().addBox(-4.0F, -6.0F, -0.5F, 2.0F, 5.0F, 1.0F, new CubeDeformation(0.0F)).mirror(false)
            .texOffs(58, 19).mirror().addBox(-2.0F, -6.0F, -0.5F, 2.0F, 5.0F, 1.0F, new CubeDeformation(0.0F)).mirror(false)
            .texOffs(56, 38).addBox(-3.0F, -1.0F, -0.5F, 3.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
            .texOffs(58, 35).addBox(-4.0F, -8.0F, -0.5F, 2.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
            .texOffs(56, 41).mirror().addBox(-4.0F, -7.0F, -0.5F, 3.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)).mirror(false), PartPose.offsetAndRotation(-1.75F, -6.5F, 0.0F, -0.2182F, 0.1309F, -0.3054F));
    }
}
